### ISSUE TITLE
Performance is not as expected (Version 3.0.0)

### ISSUE THREAD

**Issue by JeffBusterCase** [Nyerst/FastGenericNew#15]
Windows 10

![image](https://user-images.githubusercontent.com/12688410/158058573-cb497672-ce20-4e5a-8058-30d97c2381d2.png)
![image](https://user-images.githubusercontent.com/12688410/158058550-ec7fe1d8-c503-46c6-8578-3ffa13854d6b.png)

**Comment by Nyerst** [comment]
Hi, thanks for the comment.

The first call of FastNew needs a short while to compile a DynamicMethod.
Try to call it once before starting the stopwatch.

**Comment by JeffBusterCase** [comment]
It worked! But I don't think it should need a manual pre-run.
